config/routes.rb
Rails.application.routes.draw do
  get 'patients/index'
  get 'patients/new'
  get 'patients/create'
  # get 'staff_session/new'
  # get 'staff_session/create'
  # get 'staff/index'
  # get 'staff/new'
  # get 'staff/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "staff_sessions#new"
  resources :staffs, only: [:index, :new, :create]
  resources :staff_sessions, only: [:new, :create]
  resources :patients
  delete '/patients/:id', to: 'patients#destroy', as: 'delete_patient'
  delete '/logout', to: 'staff_sessions#destroy'
  get 'login', to: 'staff_sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :fullname, presence: true
  validates :age, presence: true
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_secure_password :password, validations: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= session[:staff_id] && Staff.find_by(id: session[:staff_id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :require_login
  before_action :require_login

  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    puts @patient.attributes.inspect
    if @patient.save
      redirect_to patients_path, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  # def show
  #   @patient = Patient.find(params[:id])
  # end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to patients_path, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path, notice: 'Patient was successfully deleted.'
  end

  private

  def patient_params
    params.require(:patient).permit(:fullname, :age)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def require_login
    return if current_user

    flash[:alert] = 'You must be logged in to access this page.'
    redirect_to login_path
  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  def index
    @users = Staff.all
  end

  def new
    @user = Staff.new
  end

  def create
    @staff = Staff.new(staff_params)

    if @staff.save
      flash[:notice] = 'Staff created successfully'
      redirect_to users_path
    else
      flash[:alert] = 'Staff not created'
      render :new, status: :unprocessable_entity
    end
  end

  def staff_params
    params.require(:staff).permit(:username, :password, :password_confirmation, :string)
  end
end

app/controllers/staff_session_controller.rb
class StaffSessionController < ApplicationController
  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.find_by(username: params[:staff][:username])

    if @staff&.authenticate(params[:user][:password])
      session[:staff_id] = @staff.id
      if @staff.role == 'doctor'
        redirect_to doctor_dashboard_path
      elsif @staff.role == 'receptionist'
        redirect_to receptionist_dashboard_path
      end
      redirect_to root_path
    else
      flash[:alert] = 'Login failed'
      redirect_to login_path
    end
  end
end

app/controllers/staff_sessions_controller.rb
class StaffSessionsController < ApplicationController
  def new
    @staff = Staff.new
  end

  def create
    @staff = Staff.find_by(username: params[:staff][:username])
    puts @staff.inspect

    if @staff&.authenticate(params[:staff][:password])
      session[:staff_id] = @staff.id
      # if @staff.role == 'doctor'
      #   redirect_to patients_path
      # elsif @staff.role == 'receptionist'
      #   redirect_to patients_path
      #   puts 'Login successful: Good'
      # else
      #   redirect_to root_path
      # end
      redirect_to patients_path
    else
      flash[:alert] = 'Login failed'
      puts 'Login failed: Bad'
      redirect_to login_path
    end
  end

  def destroy
    session[:staff_id] = nil
    redirect_to root_path, notice: 'Logged out successfully.'
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/staff_session_helper.rb
module StaffSessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mclinic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= form_with model: @patient, url: patient_path(@patient), method: :patch do |form| %>
  <div>
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.text_field :age, type: 'number' %>
  </div>
  <%= form.submit "Update Patient" %>
<% end %>

app/views/patients/index.html.erb
<% if current_user.role == 'receptionist' %>
  <h1>All Patients</h1>
  <ul>
    <% @patients.each do |patient| %>
      <li>
        <%= patient.fullname %> - <%= patient.age %>
        <%= link_to "Edit", edit_patient_path(patient) %>
        <%= button_to "Delete", delete_patient_path(patient), method: :delete, data: { confirm: "Are you sure?" } %>
        
      </li>
    <% end %>
    <%= link_to "Logout", logout_path, class: "button", data: { "turbo-method": :delete } %>

    <%= link_to "Add Patient", new_patient_path, class: "button" %>
  </ul>
<% else %>
  <h1>Welcome, Dr. <%= current_user.username %></h1>
  <%= line_chart Patient.group_by_day(:created_at, last: 7).count %>
  <%= link_to "Logout", logout_path, class: "button", data: { "turbo-method": :delete } %>
<% end %>

app/views/patients/new.html.erb
<h1>Add Patients</h1>

<%= form_with model: @patient, url: patients_path do |form| %>
  <div>
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.text_field :age, type: 'number' %>
  </div>
  <%= form.submit "Add Patient" %>
<% end %>

app/views/staff/create.html.erb
<h1>Staff#create</h1>
<p>Find me in app/views/staff/create.html.erb</p>

app/views/staff/index.html.erb
<h1>Staff#index</h1>
<p>Find me in app/views/staff/index.html.erb</p>

app/views/staff/new.html.erb
<h1>Staff#new</h1>
<p>Find me in app/views/staff/new.html.erb</p>

app/views/staff_sessions/create.html.erb
<h1>StaffSession#create</h1>
<p>Find me in app/views/staff_session/create.html.erb</p>

app/views/staff_sessions/new.html.erb
<h1>Login Page</h1>
<%= form_with model: @staff, url: staff_sessions_path do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <%= form.submit "Log In" %>
<% end %>